export class CartInfo {
  public static readonly cartData = [
    {
      orderNumber: 1,
      orderDueDate: 1 / 1 / 1,
      buyerName: "Ashu",
      address: "Patna",
      phoneNo: 9206287569,
      orderTotal: 25,
    },
    {
      orderNumber: 2,
      orderDueDate: 1 / 1 / 1,
      buyerName: "Atul",
      address: "Bihar",
      phoneNo: 9206287569,
      orderTotal: 25,
    },
    {
      orderNumber: 3,
      orderDueDate: 1 / 1 / 1,
      buyerName: "Rahul",
      address: "Banglore",
      phoneNo: 9206287569,
      orderTotal: 25,
    },
    {
      orderNumber: 4,
      orderDueDate: 1 / 1 / 1,
      buyerName: "Abhinav",
      address: "Delhi",
      phoneNo: 9206287569,
      orderTotal: 25,
    },
    {
      orderNumber: 5,
      orderDueDate: 1 / 1 / 1,
      buyerName: "Sourabh",
      address: "Banglore",
      phoneNo: 9206287569,
      orderTotal: 25,
    },
    {
      orderNumber: 6,
      orderDueDate: 1 / 1 / 1,
      buyerName: "Ashish",
      address: "Banglore",
      phoneNo: 9206287569,
      orderTotal: 25,
    },
    {
      orderNumber: 7,
      orderDueDate: 1 / 1 / 1,
      buyerName: "Rohit",
      address: "Bihar",
      phoneNo: 9206287569,
      orderTotal: 25,
    },
    {
      orderNumber: 8,
      orderDueDate: 1 / 1 / 1,
      buyerName: "Mohit",
      address: "Mumbai",
      phoneNo: 9206287569,
      orderTotal: 25,
    },
    {
      orderNumber: 9,
      orderDueDate: 1 / 1 / 1,
      buyerName: "Shivam",
      address: "Lucknow",
      phoneNo: 9206287569,
      orderTotal: 25,
    },
    {
      orderNumber: 10,
      orderDueDate: 1 / 1 / 1,
      buyerName: "Vinay",
      address: "Goa",
      phoneNo: 9206287569,
      orderTotal: 25,
    },
  ];
}
